const TeamData = [
  {
    id: 1,
    Name: "Hamza",
    Email: "HamzaOut@gmail.com",
    Age: 26,
    Phone: "06.20.55.32.59",
    Access: "Admin",
  },
  {
    id: 2,
    Name: "Omar",
    Email: "OmarOut@gmail.com",
    Age: 23,
    Phone: "06.45.25.62.59",
    Access: "Admin",
  },
  {
    id: 3,
    Name: "yassir",
    Email: "NmoYassir@gmail.com",
    Age: 30,
    Phone: "06.75.26.54.32",
    Access: "Admin",
  },
  {
    id: 4,
    Name: "Hamid",
    Email: "NomHamid@gmail.com",
    Age: 48,
    Phone: "06.32.59.4562",
    Access: "Manager",
  },
  {
    id: 5,
    Name: "Anoir",
    Email: "AnoirBoi21@gmail.com",
    Age: 45,
    Phone: "06.28.26.59.64",
    Access: "Manager",
  },
  {
    id: 6,
    Name: "Redoin",
    Email: "RedoinBoi21@gmail.com",
    Age: 31,
    Phone: "06.78.59.12.26",
    Access: "Manager",
  },
  {
    id: 7,
    Name: "Nohaila",
    Email: "Nohaila99@gmail.com",
    Age: 35,
    Phone: "06.20.54.65.26",
    Access: "Manager",
  },
  {
    id: 8,
    Name: "Nour",
    Email: "NourBO2@gmail.com",
    Age: 22,
    Phone: "06.13.65.98.47",
    Access: "User",
  },
  {
    id: 9,
    Name: "Raja",
    Email: "Raja55@gmail.com",
    Age: 56,
    Phone: "06.45.21.65.75",
    Access: "User",
  },
  {
    id: 10,
    Name: "saaed",
    Email: "SaaedPop@gmail.com",
    Age: 50,
    Phone: "06.45.26.59.45",
    Access: "User",
  },
];

export { TeamData };
